include: package:lint_hard/all.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.pb.dart'
    - '**/*.pbenum.dart'
    - '**/*.pbjson.dart'
    - '**/*.pbserver.dart'
linter:
  rules:
    unawaited_futures: true
    avoid_positional_boolean_parameters: false