name: coagulate
description: Staying in contact, with privacy friendly contact synchronization powered by Veilid.
publish_to: 'none'
version: "0.0.1+11"

environment:
  sdk: '>=3.0.5 <4.0.0'  
  flutter: ">=3.10.0"

dependencies:
  ansicolor: ^2.0.2
  awesome_extensions: ^2.0.16
  basic_utils: ^5.7.0
  bloc: ^8.1.4
  bloc_advanced_tools: ^0.1.4
  charcode: ^1.3.1
  collection: ^1.18.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_contacts: ^1.1.8
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.6
  flutter_platform_widgets: ^7.0.1
  flutter_svg: ^2.0.10
  formz: ^0.7.0
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  geolocator: ^10.1.1
  go_router: ^14.2.1
  hive: ^2.2.3
  intl: any
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  location_picker_flutter_map: ^3.0.1
  loggy: ^2.0.3
  mobile_scanner: ^5.1.1 # TODO: Replace with privacy friendlier alternative
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0
  radix_colors: ^1.0.4
  rxdart: ^0.28.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  signal_strength_indicator: ^0.4.1
  sqflite: ^2.3.3
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  veilid:
    #   veilid: ^0.0.1
    path: ../veilid/veilid-flutter
  veilid_support:
    path: packages/veilid_support
  # TODO: Replace with 0.5.3; 0.5.2 might also be enough if new iOS features aren't required
  workmanager:
      git:
        url: https://github.com/fluttercommunity/flutter_workmanager.git
        ref: b783000c18f6e066f3d81d5ecc352f3ce61860f6

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.6
  flutter_oss_licenses: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.1
  icons_launcher: ^2.1.3
  json_serializable: ^6.7.1
  lint_hard: ^4.0.0
  test: ^1.25.2

flutter_native_splash:
  color: "#8588D0"
  
icons_launcher:
  image_path: 'assets/launcher/icon.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#ffffff'
      adaptive_foreground_image: 'assets/launcher/icon.png'
      adaptive_round_image: 'assets/launcher/icon.png'
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    # Launcher icon
    - assets/launcher/icon.png
    # Images
    - assets/images/icon.svg
    - assets/images/title.svg
    - assets/images/up_arrow_bg.svg
    - assets/images/down_arrow_bg.svg
