name: coagulate
description: Staying in contact, with privacy friendly contact synchronization powered by Veilid.
publish_to: 'none'
version: "0.0.1"

environment:
  sdk: '>=3.0.5 <4.0.0'  
  flutter: ">=3.10.0"

dependencies:
  ansicolor: ^2.0.1
  basic_utils: ^5.6.1
  charcode: ^1.3.1
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_translate: ^4.0.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  mutex: ^3.0.1
  path: ^1.8.2
  protobuf: ^3.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.0.15
  uuid: ^4.2.1
  veilid:
    #   veilid: ^0.0.1
    path: ../veilid/veilid-flutter
  window_manager: ^0.3.5
  zxing2: ^0.2.0
  mapbox_maps_flutter: ^0.5.1
  flutter_osm_plugin: ^1.0.0-rc.2
  flutter_contacts: ^1.1.7
  pretty_json: ^2.0.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.3
  geocoding: ^2.1.1
  bloc: ^8.1.2
  path_provider: ^2.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  icons_launcher: ^2.1.3
  json_serializable: ^6.7.1
  lint_hard: ^4.0.0
  riverpod_generator: ^2.2.3

flutter_native_splash:
  color: "#8588D0"
  
icons_launcher:
  image_path: 'assets/launcher/icon.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#ffffff'
      adaptive_foreground_image: 'assets/launcher/icon.png'
      adaptive_round_image: 'assets/launcher/icon.png'
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    # Translations
    - assets/i18n/en.json
    # Launcher icon
    - assets/launcher/icon.png
    # Images
    - assets/images/splash.svg
    - assets/images/icon.svg
    - assets/images/title.svg
    - assets/images/vlogo.svg
    - assets/images/ellet.png
    # Fonts
  fonts:
    - family: Source Code Pro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
