name: coagulate
description: Staying in contact, with privacy friendly contact synchronization and location sharing powered by Veilid.
publish_to: 'none'
version: "0.1.4+0"

environment:
  sdk: '>=3.0.5 <4.0.0'  
  flutter: ">=3.10.0"

dependencies:
  ansicolor: ^2.0.2
  background_fetch: ^1.3.7
  bloc: ^8.1.4
  bloc_advanced_tools: ^0.1.4
  charcode: ^1.3.1
  collection: ^1.18.0
  equatable: ^2.0.5
  fast_immutable_collections: ^10.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_contacts: ^1.1.8
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  flutter_platform_widgets: ^7.0.1
  flutter_svg: ^2.0.10
  formz: ^0.7.0
  freezed_annotation: ^3.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  go_router: ^14.2.1
  hive: ^2.2.3
  image_picker: ^1.1.2
  intl: any
  image: ^4.0.17
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  location_picker_flutter_map: ^3.0.1
  loggy: ^2.0.3
  mobile_scanner: ^6.0.3 # TODO: Replace with privacy friendlier alternative
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0
  rxdart: ^0.28.0
  share_plus: ^10.1.4
  shared_preferences: ^2.2.3
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  uuid: ^4.4.2
  veilid:
    #   veilid: ^0.0.1
    path: ../veilid/veilid-flutter
  veilid_support:
    path: packages/veilid_support
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.3.0
  faker: ^2.2.0
  flutter_local_notifications: ^18.0.1
  phone_numbers_parser: ^9.0.3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.6
  flutter_oss_licenses: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  icons_launcher: ^2.1.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint_hard: ^4.0.0
  test: ^1.25.2

flutter_native_splash:
  color: "#8588D0"
  
icons_launcher:
  image_path: 'assets/launcher/icon.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#ffffff'
      adaptive_foreground_image: 'assets/launcher/icon.png'
      adaptive_round_image: 'assets/launcher/icon.png'
    ios:
      enable: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    # Launcher icon
    - assets/launcher/icon.png
    # Images
    - assets/images/icon.svg
    - assets/images/title.svg
    - assets/images/up_arrow_bg.svg
    - assets/images/down_arrow_bg.svg
