name: veilidchat
description: VeilidChat
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'  
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^2.1.1
  cupertino_icons: ^1.0.2
  ansicolor: ^2.0.1
  loggy: ^2.0.3
  uuid: ^3.0.7
  path: ^1.8.2
  path_provider: ^2.0.11
  veilid:
    #   veilid: ^0.0.1
    path: ../veilid/veilid-flutter
  animated_theme_switcher: ^2.0.7
  shared_preferences: ^2.0.15
  go_router: ^9.0.0
  fast_immutable_collections: ^9.1.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  change_case: ^1.1.0
  radix_colors: ^1.0.4
  flutter_translate: ^4.0.4
  intl: ^0.18.0
  fixnum: ^1.1.0
  protobuf: ^3.0.0
  charcode: ^1.3.1
  window_manager: ^0.3.5
  flutter_svg: ^2.0.7
  reorderable_grid: ^1.0.7
  circular_profile_avatar: ^2.0.5
  badges: ^3.1.1
  awesome_extensions: ^2.0.9
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  blurry_modal_progress_hud: ^1.1.0
  flutter_spinkit: ^5.2.0
  quickalert: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "assets/launcher/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 24 # android min sdk min:16, default 21
  web:
    generate: true
    background_color: "#33183f"
    theme_color: "#863fa6"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    # Translations
    - assets/i18n/en.json
    # Launcher icon
    - assets/launcher/icon.png
    # Images
    - assets/images/splash.svg
    - assets/images/icon.svg
    - assets/images/title.svg
    - assets/images/vlogo.svg
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
