name: coagulate
description: Staying in contact, with privacy friendly contact synchronization powered by Veilid.
publish_to: 'none'
version: "0.0.1"

environment:
  sdk: '>=3.0.5 <4.0.0'  
  flutter: ">=3.10.0"

dependencies:
  ansicolor: ^2.0.1
  basic_utils: ^5.6.1
  bloc: ^8.1.2
  charcode: ^1.3.1
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_contacts: ^1.1.7
  flutter_osm_plugin: ^1.0.0-rc.2
  flutter_svg: ^2.0.7
  flutter_translate: ^4.0.4
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.1
  hydrated_bloc: ^9.1.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  mapbox_maps_flutter: ^1.0.0
  mobile_scanner: ^4.0.1
  mutex: ^3.0.1
  path: ^1.8.2
  path_provider: ^2.1.2
  pretty_json: ^2.0.0
  protobuf: ^3.0.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  uuid: ^4.2.1
  veilid:
    #   veilid: ^0.0.1
    path: ../veilid/veilid-flutter
  window_manager: ^0.3.5
  workmanager: ^0.5.2
  zxing2: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  icons_launcher: ^2.1.3
  json_serializable: ^6.7.1
  lint_hard: ^4.0.0

flutter_native_splash:
  color: "#8588D0"
  
icons_launcher:
  image_path: 'assets/launcher/icon.png'
  platforms:
    android:
      enable: true
      adaptive_background_color: '#ffffff'
      adaptive_foreground_image: 'assets/launcher/icon.png'
      adaptive_round_image: 'assets/launcher/icon.png'
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    # Translations
    - assets/i18n/en.json
    # Launcher icon
    - assets/launcher/icon.png
    # Images
    - assets/images/splash.svg
    - assets/images/icon.svg
    - assets/images/title.svg
    - assets/images/vlogo.svg
    - assets/images/ellet.png
