name: async_tools
description: Useful data structures and tools for async/Future code
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.1
  mutex:
    path: ../mutex

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  lint_hard: ^4.0.0
  test: ^1.25.2
