on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Veilid
      run: cd .. && git clone https://gitlab.com/veilid/veilid.git
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.8'
    - name: Prep Mapbox Secrets
      run: |
        echo '<string name="mapbox_access_token">${{ secrets.MAPBOX_SECRET_TOKEN }}</string>' > android/app/src/main/res/values/developer-config.xml
        mkdir /home/runner/.gradle
        echo "SDK_REGISTRY_TOKEN=${{ secrets.MAPBOX_SECRET_TOKEN }}" > /home/runner/.gradle/gradle.properties
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
