on: ["push"]
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  # release:
  #   types: [published]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.1'
        channel: 'stable'
    - name: Checkout Veilid
      run: cd .. && git clone https://gitlab.com/veilid/veilid.git
    - uses: actions/checkout@v3
    - run: ls -ahl && flutter pub get
    - run: flutter build appbundle --debug

  # ios:
  #   runs-on: macos-latest
  #   steps:
  #   - name: Checkout Veilid
  #     run: cd .. && git clone https://gitlab.com/veilid/veilid.git
  #   - uses: actions/checkout@v3
  #   - uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '3.19.1'
  #   - run: flutter pub get
  #   - run: flutter build ipa
